FROM registry.access.redhat.com/hi/nginx:latest-builder AS builder

FROM registry.access.redhat.com/hi/nginx:latest-fips

# Blue v0.1.0
ENV IMAGE_ENDPOINT="http://localhost:8081/blue"
ENV BACKGROUND_COLOR="#0033cc"

# Green v0.2.0
# ENV IMAGE_ENDPOINT="http://localhost:8081/green"
# ENV BACKGROUND_COLOR="#00aa44"

COPY --from=builder /bin/sh /bin/sh
COPY --chmod=755 entrypoint.sh /entrypoint.sh
COPY index.html /usr/share/nginx/html/index.html
COPY frame.html /usr/share/nginx/html/frame.html
COPY --chmod=666 config.json /usr/share/nginx/html/config.json

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
