services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "8080:8080"
    environment:
      IMAGE_ENDPOINT: "http://localhost:8081/blue"
      BACKGROUND_COLOR: "#0033cc"
    depends_on:
      - backend
