{{- range .Values.components }}
{{- if .url }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    route.openshift.io/termination: edge
spec:
  rules:
    - host: {{ .url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .containerPort }}
{{- end }}
{{- end }}
