{{- range .Values.components }}
{{- if .roleArn }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .roleArn | quote }}
    eks.amazonaws.com/sts-regional-endpoints: "true"
{{- end }}
{{- end }}
