{{- range .Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - name: "{{ .containerPort }}-tcp"
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
{{- end }}
