# Name will be used for all k8s objects (Deployment, Service, and Ingress)
appName: blue-green-demo

# Port the application inside the container runs on
containerPort: 8080

# Container image and tag for application
image: quay.io/ryanmillerc/blue-green-demo:latest

# URL to be exposed from the cluster. This should be in the format something.apps.lab.aws.ocp.uscg.mil
url: blue-green-demo.apps.ocp.taco.moe
