components:
  - name: demo-backend
    image: quay.io/ryanmillerc/demo-backend:latest
    containerPort: 8080
    url: demo-backend.apps.ocp.taco.moe

  - name: demo-frontend
    image: quay.io/ryanmillerc/demo-frontend:latest
    containerPort: 8080
    url: demo.apps.ocp.taco.moe
    env:
      - name: BACKGROUND_COLOR
        value: "#0033cc"
      - name: IMAGE_ENDPOINT
        value: "https://demo-backend.apps.ocp.taco.moe/blue"
