components:
  - name: demo-backend
    image: quay.io/ryanmillerc/demo-backend:latest
    containerPort: 8080
    replicas: 3
    awsTokenMount: true
    url: demo-backend.apps.ocp.taco.moe
    env:
      - name: AWS_ROLE_ARN
        value: "arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME"
      - name: AWS_REGION
        value: "us-east-1"
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
      - name: S3_BUCKET_NAME
        value: "your-bucket-name"

  - name: demo-frontend
    image: quay.io/ryanmillerc/demo-frontend:latest
    containerPort: 8080
    replicas: 3
    url: demo.apps.ocp.taco.moe
    env:
      - name: BACKGROUND_COLOR
        value: "#0033cc"
      - name: IMAGE_ENDPOINT
        value: "https://demo-backend.apps.ocp.taco.moe/blue"
