apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend-dev
spec:
  source:
    type: Binary
    binary: {}
    contextDir: frontend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: frontend-dev:latest
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend-dev
spec:
  source:
    type: Binary
    binary: {}
    contextDir: backend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: backend-dev:latest
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
